### ISSUE TITLE
Icoshift link not working

### ISSUE THREAD

**Issue by andreped** [sekro/pyicoshift#1]
I tried clicking the link in the README to read about the Icoshift algorithm (this: http://www.models.life.ku.dk/icoshift).

This resulted in a PDOException error. Do you see the same? See screenshot below.

![Skjermbilde 2022-04-08 164543](https://user-images.githubusercontent.com/29090665/162462676-f0814a98-8fb7-4a0b-8d4d-9480f5047b43.png)

**Comment by sekro** [comment]
Thanks for the info! Same for me. I'll try to find a new link asap.

**Comment by sekro** [comment]
the original site appears to be down - here is a snapshot: https://web.archive.org/web/20220303211331/www.models.life.ku.dk/icoshift
